site_name: Java Tron
site_url: https://tronprotocol.github.io/documentation-zh/
repo_url: https://github.com/tronprotocol/documentation-zh

nav:
    - 入门: 
        - Java-tron入门: getting_started/getting_started_with_javatron.md
    - 使用Java-tron:
        - 部署Java-tron: using_javatron/installing_javatron.md
        - 备份和恢复: using_javatron/backup_restore.md
        - 轻节点: developers/litefullnode.md
        - 私链网络: using_javatron/private_network.md
        - 事件插件: architecture/event.md
        - 数据库配置: architecture/database.md
        - 网络配置: using_javatron/connecting_to_tron.md
        - 节点监控: using_javatron/metrics.md
        - 工具:
            - 数据库迁移: using_javatron/toolkit.md
            - 轻节点工具: using_javatron/litefullnode-tool.md
    - API 接口:
        - HTTP 接口: api/http.md
        - gRPC 接口: api/rpc.md
    - 核心协议:
        - 波场共识: introduction/dpos.md
        - 超级代表: mechanism-algorithm/sr.md
        - 账户模型: mechanism-algorithm/account.md
        - 资源模型: mechanism-algorithm/resource.md
        - 智能合约: contracts/contract.md
        - 去中心化交易所: mechanism-algorithm/dex.md
        - 多重签名: mechanism-algorithm/multi-signatures.md
    - Java-tron开发:
        - 开发者指南: developers/java-tron.md
        - TIPs工作流程: developers/tips.md
        - Issue工作流程: developers/issue-workflow.md
        - 治理流程: developers/governance.md
        - 配置IDE开发环境: developers/run-in-idea.md
        - 开发示例: developers/demo.md
        - 核心模块:
            - 概述: developers/code-structure.md
            - Chainbase: developers/chainbase.md
            - 网络: developers/network.md
    - Dapp开发:
        - Dapp开发工具: contracts/compiler.md
    - Wallet-cli: 
        - 什么是Wallet-Cli: clients/wallet-cli.md
        - Wallet命令: clients/wallet-cli-command.md
    - 版本发布:
        - 新版本部署手册: releases/upgrade-instruction.md
        - 一致性检验: releases/signature_verification.md
        - 历史版本:
            - GreatVoyage-v4.7.0.1: releases/GreatVoyage-v470.md
            - GreatVoyage-v4.6.0: releases/GreatVoyage-v460.md
            - GreatVoyage-v4.5.2: releases/GreatVoyage-v452.md
            - GreatVoyage-v4.5.1: releases/GreatVoyage-v451.md
            - GreatVoyage-v4.4.6: releases/GreatVoyage-v446.md
            - GreatVoyage-v4.4.5: releases/GreatVoyage-v445.md
            - GreatVoyage-v4.4.4: releases/GreatVoyage-v444.md
            - GreatVoyage-v4.4.2: releases/GreatVoyage-v442.md
            - GreatVoyage-v4.4.0: releases/GreatVoyage-v440.md
            - GreatVoyage-v4.3.0: releases/GreatVoyage-v430.md
            - GreatVoyage-v4.2.2.1: releases/GreatVoyage-v4221.md
            - GreatVoyage-v4.2.2: releases/GreatVoyage-v422.md
            - GreatVoyage-v4.2.0: releases/GreatVoyage-v420.md
            - GreatVoyage-v4.1.3: releases/GreatVoyage-v413.md
            - GreatVoyage-v4.1.2: releases/GreatVoyage-v412.md
            - GreatVoyage-v4.1.1: releases/GreatVoyage-v411.md
            - GreatVoyage-v4.0.0: releases/GreatVoyage-v400.md
            - Odyssey-v3.7: releases/Odyssey-v37.md
            - Odyssey-v3.6.5: releases/Odyssey-v365.md
    - 术语表: glossary.md


theme: readthedocs
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - footnotes
    - codehilite
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.tilde
    - pymdownx.tasklist
    - pymdownx.superfences
